// ============================================================
// services/routeSeeds.ts — Offline KNUST fallback seed data
// ============================================================

import { Route } from '../types';

export const KNUST_SEED_ROUTES: Route[] = [
  {
    id: 'RT-01',
    number: 'K-01',
    name: 'Tech Junction – Katanga Circular',
    color: '#1D9E75',
    startStop: 'Tech Junction',
    endStop: 'Continental Roundabout',
    intermediateStops: ['Main Gate', 'Continental Roundabout', 'Administration Block', 'Prempeh II Library', 'Great Hall', 'University Hall / Katanga'],
    status: 'Active',
    frequency: 10,
    buses: 6,
    type: 'Circular',
    direction: 'Northbound',
  },
  {
    id: 'RT-02',
    number: 'K-02',
    name: 'Halls Circular — North',
    color: '#3B82F6',
    startStop: 'Continental Roundabout',
    endStop: 'Continental Roundabout',
    intermediateStops: ['Unity Hall / Conti', 'Africa Hall', 'Queen Elizabeth II Hall', 'Independence Hall', 'Republic Hall', 'Paa Joe Stadium'],
    status: 'Active',
    frequency: 12,
    buses: 5,
    type: 'Circular',
    direction: 'Northbound',
  },
  {
    id: 'RT-03',
    number: 'K-03',
    name: 'Faculty Express',
    color: '#F59E0B',
    startStop: 'Tech Junction',
    endStop: 'Continental Roundabout',
    intermediateStops: ['Main Gate', 'College of Engineering', 'College of Science', 'KNUST School of Business / KSB', 'College of Art & Built Environment'],
    status: 'Active',
    frequency: 15,
    buses: 4,
    type: 'Express',
    direction: 'Eastbound',
  },
  {
    id: 'RT-04',
    number: 'K-04',
    name: 'Commercial Shuttle',
    color: '#8B5CF6',
    startStop: 'Continental Roundabout',
    endStop: 'Commercial Area / Market',
    intermediateStops: ['Great Hall', 'Commercial Area / Market', 'Brunei Complex', 'Non-Resident Facility / Club B', 'Botanical Gardens'],
    status: 'Active',
    frequency: 15,
    buses: 3,
    type: 'Regular',
    direction: 'Southbound',
  },
  {
    id: 'RT-05',
    number: 'K-05',
    name: 'New Site Connector',
    color: '#EC4899',
    startStop: 'Tech Junction',
    endStop: 'New Site Terminal',
    intermediateStops: ['Main Gate', 'Continental Roundabout', 'Ayeduase Junction', 'Kotei Roundabout'],
    status: 'Inactive',
    frequency: 20,
    buses: 0,
    type: 'Feeder',
    direction: 'Southbound',
  },
  {
    id: 'RT-06',
    number: 'K-06',
    name: 'Library – Stadium Loop',
    color: '#EF4444',
    startStop: 'Prempeh II Library',
    endStop: 'Prempeh II Library',
    intermediateStops: ['Administration Block', 'Great Hall', 'Republic Hall', 'Paa Joe Stadium', 'Independence Hall'],
    status: 'Active',
    frequency: 15,
    buses: 3,
    type: 'Circular',
    direction: 'Westbound',
  },
];

export const KNUST_SEED_STOPS: Record<string, { lat: number; lng: number; riders: number; zone: string }> = {
  'Tech Junction': { lat: 6.6698, lng: -1.5765, riders: 420, zone: 'Gateway' },
  'Main Gate': { lat: 6.6712, lng: -1.5749, riders: 180, zone: 'Gateway' },
  'Continental Roundabout': { lat: 6.6741, lng: -1.5716, riders: 510, zone: 'General' },
  'Administration Block': { lat: 6.6758, lng: -1.5710, riders: 120, zone: 'Academic' },
  'Prempeh II Library': { lat: 6.6769, lng: -1.5703, riders: 350, zone: 'Academic' },
  'Great Hall': { lat: 6.6754, lng: -1.5688, riders: 280, zone: 'General' },
  'University Hall / Katanga': { lat: 6.6762, lng: -1.5672, riders: 390, zone: 'Residential' },
  'Unity Hall / Conti': { lat: 6.6755, lng: -1.5730, riders: 340, zone: 'Residential' },
  'Africa Hall': { lat: 6.6763, lng: -1.5742, riders: 160, zone: 'Residential' },
  'Queen Elizabeth II Hall': { lat: 6.6771, lng: -1.5728, riders: 210, zone: 'Residential' },
  'Independence Hall': { lat: 6.6779, lng: -1.5714, riders: 290, zone: 'Residential' },
  'Republic Hall': { lat: 6.6773, lng: -1.5699, riders: 310, zone: 'Residential' },
  'Paa Joe Stadium': { lat: 6.6760, lng: -1.5695, riders: 95, zone: 'General' },
  'College of Engineering': { lat: 6.6725, lng: -1.5728, riders: 480, zone: 'Academic' },
  'College of Science': { lat: 6.6733, lng: -1.5712, riders: 410, zone: 'Academic' },
  'KNUST School of Business / KSB': { lat: 6.6740, lng: -1.5698, riders: 330, zone: 'Academic' },
  'College of Art & Built Environment': { lat: 6.6748, lng: -1.5683, riders: 150, zone: 'Academic' },
  'Commercial Area / Market': { lat: 6.6760, lng: -1.5670, riders: 450, zone: 'Gateway' },
  'Brunei Complex': { lat: 6.6766, lng: -1.5658, riders: 260, zone: 'Residential' },
  'Non-Resident Facility / Club B': { lat: 6.6750, lng: -1.5660, riders: 80, zone: 'General' },
  'Botanical Gardens': { lat: 6.6735, lng: -1.5650, riders: 60, zone: 'General' },
  'Ayeduase Junction': { lat: 6.6720, lng: -1.5680, riders: 190, zone: 'Gateway' },
  'Kotei Roundabout': { lat: 6.6705, lng: -1.5655, riders: 110, zone: 'Gateway' },
  'New Site Terminal': { lat: 6.6690, lng: -1.5638, riders: 380, zone: 'Gateway' },
};
